-- HistoGuesser Expansion: 100 More Historical Figures
-- Adds 100 additional famous historical figures across 8 categories with geographic balance
-- Categories: Politics (13), Military (13), Science (13), Religion (12), Culture (13), Exploration (12), Social (12), Business (12)
-- Geographic: Europe (40), Americas (30), Asia (20), Other (10)

INSERT INTO figures (name, aliases, images, birth_year, death_year, active_year, hometown, lat, lon, description, tags) VALUES

-- POLITICS (13 figures: 5 Europe, 5 Americas, 2 Asia, 1 Other)
('Catherine the Great', ARRAY['Catherine II', 'Catherine of Russia'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Catherine_the_Great_by_Richard_Brompton.jpg/800px-Catherine_the_Great_by_Richard_Brompton.jpg", "license": "Public Domain", "credit": "Richard Brompton", "source_url": "https://commons.wikimedia.org/wiki/File:Catherine_the_Great_by_Richard_Brompton.jpg"}]'::jsonb,
 1729, 1796, 1762, 'Stettin, Prussia', 53.4289, 14.5530,
 'German-born Empress of Russia who ruled for 34 years and expanded the Russian Empire to its largest size. Known for her enlightened reforms and numerous lovers.',
 ARRAY['politics', 'royalty', 'europe', 'female', 'russia']),

('Otto von Bismarck', ARRAY['Bismarck', 'Iron Chancellor'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Otto_von_Bismarck_1890.jpg/800px-Otto_von_Bismarck_1890.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Otto_von_Bismarck_1890.jpg"}]'::jsonb,
 1815, 1898, 1862, 'Schönhausen, Prussia', 52.5500, 12.1000,
 'Prussian statesman who unified Germany and became its first Chancellor. Master of realpolitik diplomacy who dominated European affairs for decades.',
 ARRAY['politics', 'military', 'europe', 'germany']),

('Margaret Thatcher', ARRAY['Thatcher', 'Iron Lady'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Margaret_Thatcher.png/800px-Margaret_Thatcher.png", "license": "Public Domain", "credit": "Central Office of Information", "source_url": "https://commons.wikimedia.org/wiki/File:Margaret_Thatcher.png"}]'::jsonb,
 1925, 2013, 1979, 'Grantham, England', 52.9167, -0.6333,
 'British Prime Minister who served for 11 years, the longest-serving British PM of the 20th century. Known for her conservative economic policies and Falklands War leadership.',
 ARRAY['politics', 'modern', 'europe', 'female', 'uk']),

('Charles de Gaulle', ARRAY['De Gaulle', 'General de Gaulle'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Charles_de_Gaulle-1963.jpg/800px-Charles_de_Gaulle-1963.jpg", "license": "Public Domain", "credit": "United States Army", "source_url": "https://commons.wikimedia.org/wiki/File:Charles_de_Gaulle-1963.jpg"}]'::jsonb,
 1890, 1970, 1940, 'Lille, France', 50.6292, 3.0573,
 'French general and statesman who led the Free French Forces during WWII and later served as President. Founder of the Fifth Republic.',
 ARRAY['politics', 'military', 'europe', 'france']),

('Vladimir Lenin', ARRAY['Lenin', 'Vladimir Ilyich Ulyanov'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Lenin1918.jpg/800px-Lenin1918.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Lenin1918.jpg"}]'::jsonb,
 1870, 1924, 1917, 'Simbirsk, Russia', 54.3142, 48.4031,
 'Russian revolutionary and politician who led the Bolsheviks to power in the Russian Revolution. Founder of the Soviet Union.',
 ARRAY['politics', 'revolution', 'europe', 'russia']),

('Franklin D. Roosevelt', ARRAY['FDR', 'Franklin Roosevelt'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/FDR_1944_Color_Portrait.jpg/800px-FDR_1944_Color_Portrait.jpg", "license": "Public Domain", "credit": "Library of Congress", "source_url": "https://commons.wikimedia.org/wiki/File:FDR_1944_Color_Portrait.jpg"}]'::jsonb,
 1882, 1945, 1933, 'Hyde Park, New York', 41.7922, -73.9375,
 '32nd President of the United States who led the nation through the Great Depression and most of WWII. Only president elected to four terms.',
 ARRAY['politics', 'modern', 'america', 'usa']),

('Fidel Castro', ARRAY['Castro', 'Fidel'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Fidel_Castro_in_1959.jpg/800px-Fidel_Castro_in_1959.jpg", "license": "Public Domain", "credit": "ACME News Photos", "source_url": "https://commons.wikimedia.org/wiki/File:Fidel_Castro_in_1959.jpg"}]'::jsonb,
 1926, 2016, 1959, 'Birán, Cuba', 20.5247, -75.8217,
 'Cuban revolutionary and politician who governed Cuba for nearly 50 years after leading the revolution that overthrew Batista.',
 ARRAY['politics', 'revolution', 'modern', 'america', 'cuba']),

('Che Guevara', ARRAY['Guevara', 'Che', 'Ernesto Guevara'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/CheHigh.jpg/800px-CheHigh.jpg", "license": "Public Domain", "credit": "Alba Photo", "source_url": "https://commons.wikimedia.org/wiki/File:CheHigh.jpg"}]'::jsonb,
 1928, 1967, 1959, 'Rosario, Argentina', -32.9468, -60.6393,
 'Argentine revolutionary who played a key role in the Cuban Revolution. Became a symbol of rebellion worldwide.',
 ARRAY['politics', 'revolution', 'military', 'modern', 'america', 'argentina']),

('Theodore Roosevelt', ARRAY['Teddy Roosevelt', 'Teddy'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/President_Theodore_Roosevelt%2C_1904.jpg/800px-President_Theodore_Roosevelt%2C_1904.jpg", "license": "Public Domain", "credit": "Library of Congress", "source_url": "https://commons.wikimedia.org/wiki/File:President_Theodore_Roosevelt,_1904.jpg"}]'::jsonb,
 1858, 1919, 1901, 'New York City, New York', 40.7128, -74.0060,
 '26th President of the United States known for his progressive reforms, trust-busting, and "Square Deal" policies. Also an avid outdoorsman.',
 ARRAY['politics', 'modern', 'america', 'usa']),

('Simón Bolívar', ARRAY['Bolívar', 'The Liberator'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Simon_Bolivar_by_Arturo_Michelena.jpg/800px-Simon_Bolivar_by_Arturo_Michelena.jpg", "license": "Public Domain", "credit": "Arturo Michelena", "source_url": "https://commons.wikimedia.org/wiki/File:Simon_Bolivar_by_Arturo_Michelena.jpg"}]'::jsonb,
 1783, 1830, 1810, 'Caracas, Venezuela', 10.4806, -66.9036,
 'Venezuelan military and political leader who played a key role in Latin American independence from Spain. Liberated multiple countries.',
 ARRAY['politics', 'military', 'independence', 'early_modern', 'america', 'venezuela']),

('Mao Zedong', ARRAY['Mao', 'Chairman Mao'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Mao_Zedong_1959.jpg/800px-Mao_Zedong_1959.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Mao_Zedong_1959.jpg"}]'::jsonb,
 1893, 1976, 1949, 'Shaoshan, China', 27.9167, 112.5333,
 'Chinese communist revolutionary who founded the People''s Republic of China and served as its Chairman. Led the Long March and Cultural Revolution.',
 ARRAY['politics', 'revolution', 'military', 'modern', 'asia', 'china']),

('Jawaharlal Nehru', ARRAY['Nehru', 'Pandit Nehru'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Jawaharlal_Nehru_1947.jpg/800px-Jawaharlal_Nehru_1947.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Jawaharlal_Nehru_1947.jpg"}]'::jsonb,
 1889, 1964, 1947, 'Allahabad, India', 25.4358, 81.8463,
 'First Prime Minister of independent India, serving from 1947 to 1964. Key figure in India''s independence movement and early foreign policy.',
 ARRAY['politics', 'independence', 'modern', 'asia', 'india']),

('Haile Selassie', ARRAY['Selassie', 'Ras Tafari'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Haile_Selassie_1970.jpg/800px-Haile_Selassie_1970.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Haile_Selassie_1970.jpg"}]'::jsonb,
 1892, 1975, 1930, 'Ejersa Goro, Ethiopia', 9.1450, 38.7333,
 'Emperor of Ethiopia who resisted Italian invasion in 1935. Last monarch of the Solomonic dynasty and important figure in Rastafarianism.',
 ARRAY['politics', 'royalty', 'modern', 'africa', 'ethiopia']),

-- MILITARY (13 figures: 5 Europe, 5 Americas, 2 Asia, 1 Other)
('Alexander the Great', ARRAY['Alexander III', 'Alexander of Macedon'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Alexander_the_Great_mosaic_%28cropped%29.jpg/800px-Alexander_the_Great_mosaic_%28cropped%29.jpg", "license": "Public Domain", "credit": "Roman mosaic", "source_url": "https://commons.wikimedia.org/wiki/File:Alexander_the_Great_mosaic_(cropped).jpg"}]'::jsonb,
 -356, -323, -334, 'Pella, Macedon', 40.7667, 22.5167,
 'Ancient Greek king of Macedon who created one of the largest empires in ancient history. Never lost a battle and conquered from Greece to India.',
 ARRAY['military', 'royalty', 'ancient', 'europe', 'greece']),

('Hannibal Barca', ARRAY['Hannibal', 'The Carthaginian'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Hannibal_Barca_-_Imaginary_Portrait_by_Jean-Baptiste_Despax.jpg/800px-Hannibal_Barca_-_Imaginary_Portrait_by_Jean-Baptiste_Despax.jpg", "license": "Public Domain", "credit": "Jean-Baptiste Despax", "source_url": "https://commons.wikimedia.org/wiki/File:Hannibal_Barca_-_Imaginary_Portrait_by_Jean-Baptiste_Despax.jpg"}]'::jsonb,
 -247, -183, -218, 'Carthage, Tunisia', 36.8065, 10.1815,
 'Carthaginian general and statesman who led the Carthaginian army against Rome in the Second Punic War. Famous for crossing the Alps with elephants.',
 ARRAY['military', 'ancient', 'africa', 'carthage']),

('Saladin', ARRAY['Salah ad-Din', 'Saladin Yusuf ibn Ayyub'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Saladin_and_Guy_of_Lusignan.jpg/800px-Saladin_and_Guy_of_Lusignan.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Saladin_and_Guy_of_Lusignan.jpg"}]'::jsonb,
 1138, 1193, 1187, 'Tikrit, Iraq', 34.6075, 43.6767,
 'Muslim military leader who became Sultan of Egypt and Syria. Known for his chivalry during the Crusades and recapture of Jerusalem.',
 ARRAY['military', 'politics', 'medieval', 'asia', 'egypt']),

('Richard the Lionheart', ARRAY['Richard I', 'Richard Coeur de Lion'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Richard_the_Lionheart.jpg/800px-Richard_the_Lionheart.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Richard_the_Lionheart.jpg"}]'::jsonb,
 1157, 1199, 1189, 'Oxford, England', 51.7520, -1.2577,
 'King of England who led the Third Crusade. Known for his military prowess and the legend of Robin Hood during his reign.',
 ARRAY['military', 'royalty', 'medieval', 'europe', 'england']),

('Hernán Cortés', ARRAY['Cortés', 'Conquistador Cortés'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Hern%C3%A1n_Cort%C3%A9s_by_Christophe_Gilbert_de_Vocance.jpg/800px-Hern%C3%A1n_Cort%C3%A9s_by_Christophe_Gilbert_de_Vocance.jpg", "license": "Public Domain", "credit": "Christophe Gilbert de Vocance", "source_url": "https://commons.wikimedia.org/wiki/File:Hern%C3%A1n_Cort%C3%A9s_by_Christophe_Gilbert_de_Vocance.jpg"}]'::jsonb,
 1485, 1547, 1519, 'Medellín, Spain', 38.9833, -6.0667,
 'Spanish conquistador who led the expedition that caused the fall of the Aztec Empire. Founded Mexico City on the ruins of Tenochtitlan.',
 ARRAY['military', 'exploration', 'early_modern', 'europe', 'spain']),

('Stonewall Jackson', ARRAY['Jackson', 'Thomas Jonathan Jackson'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Stonewall_Jackson_by_Neysa_McMein.jpg/800px-Stonewall_Jackson_by_Neysa_McMein.jpg", "license": "Public Domain", "credit": "Neysa McMein", "source_url": "https://commons.wikimedia.org/wiki/File:Stonewall_Jackson_by_Neysa_McMein.jpg"}]'::jsonb,
 1824, 1863, 1861, 'Clarksburg, Virginia', 39.2806, -80.3444,
 'Confederate general during the American Civil War known for his tactical brilliance and ability to appear wherever needed most.',
 ARRAY['military', 'civil_war', 'modern', 'america', 'usa']),

('Ulysses S. Grant', ARRAY['Grant', 'U.S. Grant'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Ulysses_S._Grant_1870-1880.jpg/800px-Ulysses_S._Grant_1870-1880.jpg", "license": "Public Domain", "credit": "Mathew Brady", "source_url": "https://commons.wikimedia.org/wiki/File:Ulysses_S._Grant_1870-1880.jpg"}]'::jsonb,
 1822, 1885, 1861, 'Point Pleasant, Ohio', 38.8437, -82.1371,
 'Union general who led the Union Army to victory in the Civil War. Later became the 18th President of the United States.',
 ARRAY['military', 'politics', 'civil_war', 'modern', 'america', 'usa']),

('Dwight D. Eisenhower', ARRAY['Ike', 'Dwight Eisenhower'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Dwight_D._Eisenhower%2C_official_photo_portrait%2C_May_29%2C_1959.jpg/800px-Dwight_D._Eisenhower%2C_official_photo_portrait%2C_May_29%2C_1959.jpg", "license": "Public Domain", "credit": "United States Army", "source_url": "https://commons.wikimedia.org/wiki/File:Dwight_D._Eisenhower,_official_photo_portrait,_May_29,_1959.jpg"}]'::jsonb,
 1890, 1969, 1941, 'Denison, Texas', 33.7555, -96.5367,
 'Supreme Commander of Allied Forces in Europe during WWII. Later became the 34th President of the United States.',
 ARRAY['military', 'politics', 'modern', 'america', 'usa']),

('Erwin Rommel', ARRAY['Rommel', 'Desert Fox'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Bundesarchiv_Bild_101III-ZS-161-25%2C_Afrika%2C_Erwin_Rommel.jpg/800px-Bundesarchiv_Bild_101III-ZS-161-25%2C_Afrika%2C_Erwin_Rommel.jpg", "license": "Public Domain", "credit": "Bundesarchiv", "source_url": "https://commons.wikimedia.org/wiki/File:Bundesarchiv_Bild_101III-ZS-161-25,_Afrika,_Erwin_Rommel.jpg"}]'::jsonb,
 1891, 1944, 1941, 'Heidenheim, Germany', 48.6783, 10.1516,
 'German Field Marshal known for his leadership in North Africa during WWII. Nicknamed the "Desert Fox" for his tactical brilliance.',
 ARRAY['military', 'modern', 'europe', 'germany']),

('Douglas MacArthur', ARRAY['MacArthur', 'General MacArthur'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/MacArthur_in_1945.jpg/800px-MacArthur_in_1945.jpg", "license": "Public Domain", "credit": "United States Army", "source_url": "https://commons.wikimedia.org/wiki/File:MacArthur_in_1945.jpg"}]'::jsonb,
 1880, 1964, 1941, 'Little Rock, Arkansas', 34.7465, -92.2896,
 'American five-star general who played a prominent role in the Pacific theater during WWII. Commander of Allied forces in the Southwest Pacific.',
 ARRAY['military', 'modern', 'america', 'usa']),

('T.E. Lawrence', ARRAY['Lawrence of Arabia', 'Lawrence'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Lowell_Thomas%2C_T.E._Lawrence%2C_1918.jpg/800px-Lowell_Thomas%2C_T.E._Lawrence%2C_1918.jpg", "license": "Public Domain", "credit": "Lowell Thomas", "source_url": "https://commons.wikimedia.org/wiki/File:Lowell_Thomas,_T.E._Lawrence,_1918.jpg"}]'::jsonb,
 1888, 1935, 1916, 'Tremadog, Wales', 52.9333, -4.1333,
 'British officer who became a legendary figure during the Arab revolt against the Ottoman Empire in WWI. Subject of the film "Lawrence of Arabia".',
 ARRAY['military', 'exploration', 'modern', 'europe', 'uk']),

('Isoroku Yamamoto', ARRAY['Yamamoto', 'Admiral Yamamoto'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Isoroku_Yamamoto.jpg/800px-Isoroku_Yamamoto.jpg", "license": "Public Domain", "credit": "Imperial Japanese Navy", "source_url": "https://commons.wikimedia.org/wiki/File:Isoroku_Yamamoto.jpg"}]'::jsonb,
 1884, 1943, 1941, 'Nagaoka, Japan', 37.4500, 138.8500,
 'Japanese admiral who planned the attack on Pearl Harbor. Commander-in-Chief of the Combined Fleet during WWII.',
 ARRAY['military', 'modern', 'asia', 'japan']),

('Vo Nguyen Giap', ARRAY['Giap', 'General Giap'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Vo_Nguyen_Giap_1946.jpg/800px-Vo_Nguyen_Giap_1946.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Vo_Nguyen_Giap_1946.jpg"}]'::jsonb,
 1911, 2013, 1945, 'An Xa, Vietnam', 19.8333, 105.7833,
 'Vietnamese military strategist and politician who masterminded victories against France and the United States. Considered one of the greatest military commanders of the 20th century.',
 ARRAY['military', 'politics', 'modern', 'asia', 'vietnam']),

-- SCIENCE (13 figures: 5 Europe, 5 Americas, 2 Asia, 1 Other)
('Archimedes', ARRAY['Archimedes of Syracuse'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Archimedes_%28Ganymede%29.jpg/800px-Archimedes_%28Ganymede%29.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Archimedes_(Ganymede).jpg"}]'::jsonb,
 -287, -212, -250, 'Syracuse, Sicily', 37.0755, 15.2866,
 'Ancient Greek mathematician, physicist, and engineer. Discovered the principles of buoyancy and invented numerous mechanical devices.',
 ARRAY['scientist', 'mathematician', 'ancient', 'europe', 'greece']),

('Copernicus', ARRAY['Nicolaus Copernicus', 'Copernicus'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Nikolaus_Kopernikus.jpg/800px-Nikolaus_Kopernikus.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Nikolaus_Kopernikus.jpg"}]'::jsonb,
 1473, 1543, 1514, 'Toruń, Poland', 53.0138, 18.5981,
 'Polish astronomer who formulated the heliocentric model of the universe. His work revolutionized astronomy and laid the foundation for modern science.',
 ARRAY['scientist', 'astronomer', 'renaissance', 'europe', 'poland']),

('Antonie van Leeuwenhoek', ARRAY['Leeuwenhoek', 'Father of Microbiology'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Antonie_van_Leeuwenhoek_%281632-1723%29.jpg/800px-Antonie_van_Leeuwenhoek_%281632-1723%29.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Antonie_van_Leeuwenhoek_(1632-1723).jpg"}]'::jsonb,
 1632, 1723, 1670, 'Delft, Netherlands', 52.0116, 4.3571,
 'Dutch microscopist who made groundbreaking discoveries in microbiology. First to observe bacteria, sperm cells, and blood cells.',
 ARRAY['scientist', 'microbiologist', 'early_modern', 'europe', 'netherlands']),

('Carl Linnaeus', ARRAY['Linnaeus', 'Father of Taxonomy'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Carl_von_Linn%C3%A9%2C_Portrait.jpg/800px-Carl_von_Linn%C3%A9%2C_Portrait.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Carl_von_Linn%C3%A9,_Portrait.jpg"}]'::jsonb,
 1707, 1778, 1735, 'Råshult, Sweden', 56.5333, 13.6667,
 'Swedish botanist who created the modern system of naming organisms. His binomial nomenclature system is still used today.',
 ARRAY['scientist', 'botanist', 'early_modern', 'europe', 'sweden']),

('Alfred Nobel', ARRAY['Nobel'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Alfred_Nobel_by_Nordisk_familjebok.png/800px-Alfred_Nobel_by_Nordisk_familjebok.png", "license": "Public Domain", "credit": "Nordisk familjebok", "source_url": "https://commons.wikimedia.org/wiki/File:Alfred_Nobel_by_Nordisk_familjebok.png"}]'::jsonb,
 1833, 1896, 1867, 'Stockholm, Sweden', 59.3293, 18.0686,
 'Swedish chemist and inventor who discovered dynamite. Established the Nobel Prizes to recognize achievements in science and peace.',
 ARRAY['scientist', 'inventor', 'chemist', 'early_modern', 'europe', 'sweden', 'nobel_prize']),

('Thomas Edison', ARRAY['Edison', 'The Wizard of Menlo Park'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Thomas_Edison2.jpg/800px-Thomas_Edison2.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Thomas_Edison2.jpg"}]'::jsonb,
 1847, 1931, 1879, 'Milan, Ohio', 41.2978, -82.6054,
 'American inventor who developed many devices that greatly influenced life around the world. Holds 1,093 patents, including the practical electric light bulb.',
 ARRAY['scientist', 'inventor', 'modern', 'america', 'usa']),

('Nikola Tesla', ARRAY['Tesla'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/N.Tesla.JPG/800px-N.Tesla.JPG", "license": "Public Domain", "credit": "Napoleon Sarony", "source_url": "https://commons.wikimedia.org/wiki/File:N.Tesla.JPG"}]'::jsonb,
 1856, 1943, 1893, 'Smiljan, Croatia', 44.5511, 15.3164,
 'Serbian-American inventor and electrical engineer who pioneered the alternating current (AC) electricity system. Made groundbreaking contributions to electromagnetism.',
 ARRAY['inventor', 'scientist', 'engineer', 'modern', 'europe']),

('Linus Pauling', ARRAY['Pauling'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Linus_Pauling.jpg/800px-Linus_Pauling.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Linus_Pauling.jpg"}]'::jsonb,
 1901, 1994, 1931, 'Portland, Oregon', 45.5152, -122.6784,
 'American chemist who won the Nobel Prize in Chemistry for his work on chemical bonds and the Nobel Peace Prize for his anti-nuclear activism.',
 ARRAY['scientist', 'chemist', 'modern', 'america', 'usa', 'nobel_laureate']),

('Richard Feynman', ARRAY['Feynman'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Richard_Feynman.jpg/800px-Richard_Feynman.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Richard_Feynman.jpg"}]'::jsonb,
 1918, 1988, 1942, 'Queens, New York', 40.7282, -73.7949,
 'American theoretical physicist known for his work in quantum mechanics and particle physics. Nobel Prize winner and famous for his Feynman diagrams.',
 ARRAY['scientist', 'physicist', 'modern', 'america', 'usa', 'nobel_laureate']),

('Carl Sagan', ARRAY['Sagan'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Carl_Sagan_Planetary_Society.JPG/800px-Carl_Sagan_Planetary_Society.JPG", "license": "Public Domain", "credit": "The Planetary Society", "source_url": "https://commons.wikimedia.org/wiki/File:Carl_Sagan_Planetary_Society.JPG"}]'::jsonb,
 1934, 1996, 1960, 'Brooklyn, New York', 40.6782, -73.9442,
 'American astronomer and science communicator. Popularized science through books and the TV series "Cosmos". Involved in Voyager Golden Record project.',
 ARRAY['scientist', 'astronomer', 'modern', 'america', 'usa']),

('J. Robert Oppenheimer', ARRAY['Oppenheimer', 'Father of the Atomic Bomb'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/JROppenheimer-LosAlamos.jpg/800px-JROppenheimer-LosAlamos.jpg", "license": "Public Domain", "credit": "Los Alamos National Laboratory", "source_url": "https://commons.wikimedia.org/wiki/File:JROppenheimer-LosAlamos.jpg"}]'::jsonb,
 1904, 1967, 1942, 'New York City, New York', 40.7128, -74.0060,
 'American theoretical physicist who directed the Manhattan Project. Known as the "father of the atomic bomb" and later advocated for nuclear control.',
 ARRAY['scientist', 'physicist', 'modern', 'america', 'usa']),

('Subrahmanyan Chandrasekhar', ARRAY['Chandra', 'Chandrasekhar'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Subrahmanyan_Chandrasekhar.jpg/800px-Subrahmanyan_Chandrasekhar.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Subrahmanyan_Chandrasekhar.jpg"}]'::jsonb,
 1910, 1995, 1930, 'Lahore, India', 31.5204, 74.3587,
 'Indian-American astrophysicist who won the Nobel Prize for his theoretical work on stellar structure and evolution. The Chandrasekhar limit is named after him.',
 ARRAY['scientist', 'astrophysicist', 'modern', 'asia', 'india', 'nobel_laureate']),

('Hideki Yukawa', ARRAY['Yukawa'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Hideki_Yukawa.jpg/800px-Hideki_Yukawa.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Hideki_Yukawa.jpg"}]'::jsonb,
 1907, 1981, 1935, 'Tokyo, Japan', 35.6762, 139.6503,
 'Japanese theoretical physicist who won the Nobel Prize for predicting the existence of mesons. First Japanese Nobel laureate in physics.',
 ARRAY['scientist', 'physicist', 'modern', 'asia', 'japan', 'nobel_laureate']),

-- RELIGION (12 figures: 5 Europe, 4 Americas, 2 Asia, 1 Other)
('Augustine of Hippo', ARRAY['Saint Augustine', 'Augustine'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Saint_Augustine_by_Philippe_de_Champaigne.jpg/800px-Saint_Augustine_by_Philippe_de_Champaigne.jpg", "license": "Public Domain", "credit": "Philippe de Champaigne", "source_url": "https://commons.wikimedia.org/wiki/File:Saint_Augustine_by_Philippe_de_Champaigne.jpg"}]'::jsonb,
 354, 430, 397, 'Thagaste, Algeria', 35.7833, 7.1167,
 'Early Christian theologian and philosopher whose writings influenced Western Christianity. Author of "Confessions" and "City of God".',
 ARRAY['religion', 'philosophy', 'ancient', 'africa', 'christianity']),

('Francis of Assisi', ARRAY['Saint Francis', 'Francis'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Saint_Francis_of_Assisi_-_Sistine_Chapel.jpg/800px-Saint_Francis_of_Assisi_-_Sistine_Chapel.jpg", "license": "Public Domain", "credit": "Sistine Chapel", "source_url": "https://commons.wikimedia.org/wiki/File:Saint_Francis_of_Assisi_-_Sistine_Chapel.jpg"}]'::jsonb,
 1181, 1226, 1209, 'Assisi, Italy', 43.0700, 12.6178,
 'Italian Catholic friar who founded the Franciscan Order. Known for his love of nature, poverty, and care for animals. Patron saint of animals and ecology.',
 ARRAY['religion', 'medieval', 'europe', 'italy', 'christianity']),

('Martin Luther', ARRAY['Luther'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Martin_Luther_by_Lucas_Cranach_d.%C3%84._1528.jpg/800px-Martin_Luther_by_Lucas_Cranach_d.%C3%84._1528.jpg", "license": "Public Domain", "credit": "Lucas Cranach the Elder", "source_url": "https://commons.wikimedia.org/wiki/File:Martin_Luther_by_Lucas_Cranach_d.%C3%84._1528.jpg"}]'::jsonb,
 1483, 1546, 1517, 'Eisleben, Germany', 51.5267, 11.5489,
 'German monk who initiated the Protestant Reformation. Posted his 95 Theses criticizing the Catholic Church, fundamentally changing Christianity.',
 ARRAY['religion', 'reformation', 'renaissance', 'europe', 'germany', 'christianity']),

('Ignatius Loyola', ARRAY['Saint Ignatius', 'Loyola'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ignatius_of_Loyola.jpg/800px-Ignatius_of_Loyola.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Ignatius_of_Loyola.jpg"}]'::jsonb,
 1491, 1556, 1540, 'Loyola, Spain', 42.8500, -2.1833,
 'Spanish priest and theologian who founded the Jesuit order. Known for his Spiritual Exercises and role in the Counter-Reformation.',
 ARRAY['religion', 'renaissance', 'europe', 'spain', 'christianity']),

('John Calvin', ARRAY['Calvin'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/John_Calvin_by_Holbein.jpg/800px-John_Calvin_by_Holbein.jpg", "license": "Public Domain", "credit": "Hans Holbein the Younger", "source_url": "https://commons.wikimedia.org/wiki/File:John_Calvin_by_Holbein.jpg"}]'::jsonb,
 1509, 1564, 1536, 'Noyon, France', 49.4833, 3.0000,
 'French theologian and pastor who developed Calvinist theology. His ideas formed the basis of Presbyterianism and influenced Protestant thought.',
 ARRAY['religion', 'theology', 'renaissance', 'europe', 'france', 'christianity']),

('Mother Teresa', ARRAY['Teresa', 'Saint Teresa of Calcutta'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Mother_Teresa_1.jpg/800px-Mother_Teresa_1.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Mother_Teresa_1.jpg"}]'::jsonb,
 1910, 1997, 1950, 'Skopje, Macedonia', 41.9981, 21.4254,
 'Albanian-Indian Catholic nun who founded the Missionaries of Charity. Won the Nobel Peace Prize for her humanitarian work with the poor.',
 ARRAY['religion', 'humanitarian', 'modern', 'europe', 'albania', 'christianity', 'nobel_laureate']),

('Billy Graham', ARRAY['Graham'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Billy_Graham_1966.jpg/800px-Billy_Graham_1966.jpg", "license": "Public Domain", "credit": "United States Information Agency", "source_url": "https://commons.wikimedia.org/wiki/File:Billy_Graham_1966.jpg"}]'::jsonb,
 1918, 2018, 1947, 'Charlotte, North Carolina', 35.2271, -80.8431,
 'American evangelist who became one of the most influential Christian leaders of the 20th century. Preached to millions through his crusades worldwide.',
 ARRAY['religion', 'evangelist', 'modern', 'america', 'usa', 'christianity']),

('Pope John Paul II', ARRAY['John Paul II', 'Karol Wojtyła'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pope_John_Paul_II_2003-09-28.jpg/800px-Pope_John_Paul_II_2003-09-28.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Pope_John_Paul_II_2003-09-28.jpg"}]'::jsonb,
 1920, 2005, 1978, 'Wadowice, Poland', 49.8833, 19.4833,
 'Pope from 1978 to 2005, the second-longest pontificate in history. Played a key role in the fall of communism in Eastern Europe.',
 ARRAY['religion', 'politics', 'modern', 'europe', 'poland', 'christianity']),

('Desmond Tutu', ARRAY['Tutu', 'Archbishop Tutu'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Desmond_Tutu_2004_Trinity_College_Dublin.jpg/800px-Desmond_Tutu_2004_Trinity_College_Dublin.jpg", "license": "CC BY 2.0", "credit": "David Shankbone", "source_url": "https://commons.wikimedia.org/wiki/File:Desmond_Tutu_2004_Trinity_College_Dublin.jpg"}]'::jsonb,
 1931, 2021, 1986, 'Klerksdorp, South Africa', -26.8521, 26.6667,
 'South African Anglican bishop who won the Nobel Peace Prize for his opposition to apartheid. First black Archbishop of Cape Town.',
 ARRAY['religion', 'activist', 'modern', 'africa', 'south_africa', 'christianity', 'nobel_laureate']),

('Dalai Lama XIV', ARRAY['Tenzin Gyatso', 'Dalai Lama'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Dalailama1_20121014_4639.jpg/800px-Dalailama1_20121014_4639.jpg", "license": "CC BY-SA 3.0", "credit": "Office of Tibet", "source_url": "https://commons.wikimedia.org/wiki/File:Dalailama1_20121014_4639.jpg"}]'::jsonb,
 1935, NULL, 1950, 'Taktser, Tibet', 36.7000, 101.7667,
 'Spiritual leader of Tibetan Buddhism and head of the Tibetan government-in-exile. Won the Nobel Peace Prize for his non-violent struggle for Tibetan autonomy.',
 ARRAY['religion', 'politics', 'modern', 'asia', 'tibet', 'buddhism', 'nobel_laureate']),

('Muhammad', ARRAY['Prophet Muhammad', 'Muhammad ibn Abdullah'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/A_Sana%27a_manuscript.jpg/800px-A_Sana%27a_manuscript.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:A_Sana%27a_manuscript.jpg"}]'::jsonb,
 570, 632, 610, 'Mecca, Saudi Arabia', 21.3891, 39.8579,
 'Arab religious, social, and political leader who founded Islam. Considered by Muslims to be the final prophet sent by God to guide humanity.',
 ARRAY['religion', 'politics', 'ancient', 'asia', 'saudi_arabia', 'islam']),

('Gautama Buddha', ARRAY['Buddha', 'Siddhartha Gautama'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Buddha_statue_2.jpg/800px-Buddha_statue_2.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Buddha_statue_2.jpg"}]'::jsonb,
 -563, -483, -528, 'Lumbini, Nepal', 27.4678, 83.2767,
 'Founder of Buddhism who achieved enlightenment and taught a path to end suffering. His teachings form the foundation of Buddhist philosophy.',
 ARRAY['religion', 'philosophy', 'ancient', 'asia', 'nepal', 'buddhism']),

-- CULTURE (13 figures: 5 Europe, 5 Americas, 2 Asia, 1 Other)
('Michelangelo Buonarroti', ARRAY['Michelangelo'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/800px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg", "license": "Public Domain", "credit": "Michelangelo", "source_url": "https://commons.wikimedia.org/wiki/File:Michelangelo_-_Creation_of_Adam_(cropped).jpg"}]'::jsonb,
 1475, 1564, 1508, 'Caprese Michelangelo, Italy', 43.6333, 12.1667,
 'Italian Renaissance sculptor, painter, architect, and poet. Created the Sistine Chapel ceiling and the statue of David.',
 ARRAY['artist', 'sculptor', 'renaissance', 'europe', 'italy']),

('Ludwig van Beethoven', ARRAY['Beethoven'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Beethoven.jpg/800px-Beethoven.jpg", "license": "Public Domain", "credit": "Joseph Karl Stieler", "source_url": "https://commons.wikimedia.org/wiki/File:Beethoven.jpg"}]'::jsonb,
 1770, 1827, 1800, 'Bonn, Germany', 50.7344, 7.0955,
 'German composer and pianist who bridged the Classical and Romantic periods. Composed 9 symphonies including the iconic 9th, despite becoming deaf.',
 ARRAY['composer', 'musician', 'early_modern', 'europe', 'germany']),

('Frédéric Chopin', ARRAY['Chopin'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Chopin-Pleyel.jpg/800px-Chopin-Pleyel.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Chopin-Pleyel.jpg"}]'::jsonb,
 1810, 1849, 1830, 'Żelazowa Wola, Poland', 52.2500, 20.6167,
 'Polish composer and pianist of the Romantic era. Known for his piano works including nocturnes, études, and preludes. Master of melody.',
 ARRAY['composer', 'musician', 'piano', 'early_modern', 'europe', 'poland']),

('Vincent van Gogh', ARRAY['Van Gogh'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg/800px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg", "license": "Public Domain", "credit": "Vincent van Gogh", "source_url": "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg"}]'::jsonb,
 1853, 1890, 1888, 'Zundert, Netherlands', 51.4714, 4.6589,
 'Dutch Post-Impressionist painter whose work had far-reaching influence on 20th century art. Created over 2,000 artworks including The Starry Night.',
 ARRAY['artist', 'painter', 'modern', 'europe', 'netherlands']),

('Johann Sebastian Bach', ARRAY['Bach', 'JS Bach'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Johann_Sebastian_Bach.jpg/800px-Johann_Sebastian_Bach.jpg", "license": "Public Domain", "credit": "Elias Gottlob Haussmann", "source_url": "https://commons.wikimedia.org/wiki/File:Johann_Sebastian_Bach.jpg"}]'::jsonb,
 1685, 1750, 1720, 'Eisenach, Germany', 50.9803, 10.3158,
 'German Baroque composer whose works include the Brandenburg Concertos and The Well-Tempered Clavier. Considered one of the greatest composers in history.',
 ARRAY['composer', 'musician', 'baroque', 'early_modern', 'europe', 'germany']),

('Mark Twain', ARRAY['Twain', 'Samuel Clemens'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Mark_Twain_by_AF_Bradley.jpg/800px-Mark_Twain_by_AF_Bradley.jpg", "license": "Public Domain", "credit": "A.F. Bradley", "source_url": "https://commons.wikimedia.org/wiki/File:Mark_Twain_by_AF_Bradley.jpg"}]'::jsonb,
 1835, 1910, 1870, 'Florida, Missouri', 39.4894, -91.7867,
 'American writer and humorist famous for "The Adventures of Tom Sawyer" and "Adventures of Huckleberry Finn". Pioneer of American literature.',
 ARRAY['writer', 'author', 'humorist', 'modern', 'america', 'usa']),

('Ernest Hemingway', ARRAY['Hemingway'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/ErnestHemingway.jpg/800px-ErnestHemingway.jpg", "license": "Public Domain", "credit": "Yousuf Karsh", "source_url": "https://commons.wikimedia.org/wiki/File:ErnestHemingway.jpg"}]'::jsonb,
 1899, 1961, 1926, 'Oak Park, Illinois', 41.8850, -87.7844,
 'American novelist and short-story writer whose style influenced 20th-century fiction. Won Nobel Prize and Pulitzer for works like "The Old Man and the Sea".',
 ARRAY['writer', 'author', 'modern', 'america', 'usa', 'nobel_laureate']),

('Louis Armstrong', ARRAY['Armstrong', 'Satchmo'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Louis_Armstrong_restored.jpg/800px-Louis_Armstrong_restored.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Louis_Armstrong_restored.jpg"}]'::jsonb,
 1901, 1971, 1920, 'New Orleans, Louisiana', 29.9511, -90.0715,
 'American jazz trumpeter and singer who revolutionized jazz music. Known for his distinctive gravelly voice and virtuosic trumpet playing.',
 ARRAY['musician', 'jazz', 'singer', 'modern', 'america', 'usa']),

('Charlie Chaplin', ARRAY['Chaplin', 'The Tramp'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Charlie_Chaplin_portrait.jpg/800px-Charlie_Chaplin_portrait.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Charlie_Chaplin_portrait.jpg"}]'::jsonb,
 1889, 1977, 1914, 'London, England', 51.5074, -0.1278,
 'English comic actor and filmmaker who became one of the most famous figures in cinema history. Created the iconic "Little Tramp" character.',
 ARRAY['actor', 'filmmaker', 'comedy', 'modern', 'europe', 'england']),

('Toni Morrison', ARRAY['Morrison'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Toni_Morrison_2008-2.jpg/800px-Toni_Morrison_2008-2.jpg", "license": "Public Domain", "credit": "U.S. Department of State", "source_url": "https://commons.wikimedia.org/wiki/File:Toni_Morrison_2008-2.jpg"}]'::jsonb,
 1931, 2019, 1970, 'Lorain, Ohio', 41.4528, -82.1824,
 'American novelist who explored the African-American experience. Won Nobel Prize in Literature and Pulitzer for "Beloved".',
 ARRAY['writer', 'author', 'modern', 'america', 'usa', 'nobel_laureate', 'female']),

('Rabindranath Tagore', ARRAY['Tagore', 'Gurudev'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Rabindranath_Tagore_unknown_location.jpg/800px-Rabindranath_Tagore_unknown_location.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Rabindranath_Tagore_unknown_location.jpg"}]'::jsonb,
 1861, 1941, 1910, 'Kolkata, India', 22.5726, 88.3639,
 'Indian poet, philosopher, and nationalist who became the first non-European to win the Nobel Prize in Literature. Composed India''s national anthem.',
 ARRAY['writer', 'poet', 'philosopher', 'modern', 'asia', 'india', 'nobel_laureate']),

('Yasunari Kawabata', ARRAY['Kawabata'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Yasunari_Kawabata_1968.jpg/800px-Yasunari_Kawabata_1968.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Yasunari_Kawabata_1968.jpg"}]'::jsonb,
 1899, 1972, 1930, 'Osaka, Japan', 34.6937, 135.5023,
 'Japanese writer who won the Nobel Prize in Literature. Known for his lyrical style and works like "Snow Country" and "The Master of Go".',
 ARRAY['writer', 'author', 'modern', 'asia', 'japan', 'nobel_laureate']),

('Amelia Earhart', ARRAY['Earhart'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Amelia_Earhart_1935.jpg/800px-Amelia_Earhart_1935.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Amelia_Earhart_1935.jpg"}]'::jsonb,
 1897, 1937, 1928, 'Atchison, Kansas', 39.5681, -95.1219,
 'American aviation pioneer and author who became the first woman to fly solo across the Atlantic Ocean. Disappeared during attempt to circumnavigate globe.',
 ARRAY['aviator', 'author', 'exploration', 'modern', 'america', 'usa', 'female']),

-- EXPLORATION (12 figures: 5 Europe, 4 Americas, 2 Asia, 1 Other)
('Marco Polo', ARRAY['Polo'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Marco_Polo_portrait.jpg/800px-Marco_Polo_portrait.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Marco_Polo_portrait.jpg"}]'::jsonb,
 1254, 1324, 1275, 'Venice, Italy', 45.4408, 12.3155,
 'Italian merchant and explorer who traveled extensively in Asia. His accounts of the East inspired European exploration and the Silk Road trade.',
 ARRAY['explorer', 'merchant', 'medieval', 'europe', 'italy']),

('Christopher Columbus', ARRAY['Columbus'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Christopher_Columbus_by_Sebastiano_del_Piombo.jpg/800px-Christopher_Columbus_by_Sebastiano_del_Piombo.jpg", "license": "Public Domain", "credit": "Sebastiano del Piombo", "source_url": "https://commons.wikimedia.org/wiki/File:Christopher_Columbus_by_Sebastiano_del_Piombo.jpg"}]'::jsonb,
 1451, 1506, 1492, 'Genoa, Italy', 44.4056, 8.9463,
 'Italian explorer who completed four voyages across the Atlantic Ocean. Opened the Americas to European exploration and colonization.',
 ARRAY['explorer', 'navigator', 'renaissance', 'europe', 'italy']),

('Ferdinand Magellan', ARRAY['Magellan'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Ferdinand_Magellan.jpg/800px-Ferdinand_Magellan.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Ferdinand_Magellan.jpg"}]'::jsonb,
 1480, 1521, 1519, 'Sabrosa, Portugal', 41.2667, -7.5833,
 'Portuguese explorer who organized the first expedition to sail around the world. The first person to cross the Pacific Ocean.',
 ARRAY['explorer', 'navigator', 'renaissance', 'europe', 'portugal']),

('James Cook', ARRAY['Captain Cook'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Captain_James_Cook_portrait.jpg/800px-Captain_James_Cook_portrait.jpg", "license": "Public Domain", "credit": "Nathaniel Dance-Holland", "source_url": "https://commons.wikimedia.org/wiki/File:Captain_James_Cook_portrait.jpg"}]'::jsonb,
 1728, 1779, 1768, 'Marton, England', 54.5333, -1.2000,
 'British explorer and navigator who mapped much of the Pacific Ocean. Made three voyages that greatly expanded European knowledge of the world.',
 ARRAY['explorer', 'navigator', 'scientist', 'early_modern', 'europe', 'england']),

('Lewis and Clark', ARRAY['Lewis', 'Clark', 'Corps of Discovery'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Lewis_and_Clark_statue.jpg/800px-Lewis_and_Clark_statue.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Lewis_and_Clark_statue.jpg"}]'::jsonb,
 1804, 1806, 1804, 'St. Louis, Missouri', 38.6270, -90.1994,
 'American expedition led by Meriwether Lewis and William Clark that explored the western United States. Commissioned by President Thomas Jefferson.',
 ARRAY['explorer', 'military', 'early_modern', 'america', 'usa']),

('Roald Amundsen', ARRAY['Amundsen'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Roald_Amundsen.jpg/800px-Roald_Amundsen.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Roald_Amundsen.jpg"}]'::jsonb,
 1872, 1928, 1911, 'Borge, Norway', 59.2167, 10.8167,
 'Norwegian explorer who was the first person to reach the South Pole. Also the first to traverse the Northwest Passage.',
 ARRAY['explorer', 'polar', 'modern', 'europe', 'norway']),

('Ernest Shackleton', ARRAY['Shackleton'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Ernest_Shackleton.jpg/800px-Ernest_Shackleton.jpg", "license": "Public Domain", "credit": "John Robert Francis", "source_url": "https://commons.wikimedia.org/wiki/File:Ernest_Shackleton.jpg"}]'::jsonb,
 1874, 1922, 1907, 'Kilkea, Ireland', 52.9167, -6.7500,
 'Irish-British Antarctic explorer famous for the Endurance expedition. Known for his leadership and survival stories in extreme conditions.',
 ARRAY['explorer', 'antarctic', 'modern', 'europe', 'ireland']),

('Howard Carter', ARRAY['Carter'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Howard_Carter_1924.jpg/800px-Howard_Carter_1924.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Howard_Carter_1924.jpg"}]'::jsonb,
 1874, 1939, 1922, 'Swaffham, England', 52.6500, 0.6833,
 'English archaeologist who discovered Tutankhamun''s tomb in Egypt''s Valley of the Kings. One of the most famous archaeological discoveries.',
 ARRAY['archaeologist', 'explorer', 'modern', 'europe', 'england']),

('Jacque Cousteau', ARRAY['Cousteau', 'Captain Cousteau'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Jacques_Cousteau_1985.jpg/800px-Jacques_Cousteau_1985.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Jacques_Cousteau_1985.jpg"}]'::jsonb,
 1910, 1997, 1943, 'Saint-André-de-Cubzac, France', 45.0000, -0.4500,
 'French naval officer and oceanographer who co-invented the aqualung. Pioneered marine conservation and underwater filming.',
 ARRAY['explorer', 'oceanographer', 'scientist', 'modern', 'europe', 'france']),

('Ranulph Fiennes', ARRAY['Fiennes', 'Sir Ranulph Fiennes'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Sir_Ranulph_Fiennes.jpg/800px-Sir_Ranulph_Fiennes.jpg", "license": "CC BY-SA 2.0", "credit": "Tim Pierce", "source_url": "https://commons.wikimedia.org/wiki/File:Sir_Ranulph_Fiennes.jpg"}]'::jsonb,
 1944, NULL, 1969, 'Windsor, England', 51.4839, -0.6044,
 'British adventurer who holds several endurance records. First person to visit both poles and cross Antarctica on foot.',
 ARRAY['explorer', 'adventurer', 'modern', 'europe', 'england']),

('Zheng He', ARRAY['Zheng He', 'Cheng Ho'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Zheng_He.jpg/800px-Zheng_He.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Zheng_He.jpg"}]'::jsonb,
 1371, 1433, 1405, 'Kunyang, China', 24.6667, 103.2500,
 'Chinese mariner and explorer who led seven expeditions to the Indian Ocean. Commanded the largest wooden ships in history.',
 ARRAY['explorer', 'navigator', 'early_modern', 'asia', 'china']),

('Ibn Battuta', ARRAY['Battuta'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Ibn_Battuta.jpg/800px-Ibn_Battuta.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Ibn_Battuta.jpg"}]'::jsonb,
 1304, 1368, 1325, 'Tangier, Morocco', 35.7595, -5.8340,
 'Moroccan explorer and scholar who traveled extensively across the Islamic world and beyond. His journeys covered over 120,000 km.',
 ARRAY['explorer', 'scholar', 'medieval', 'africa', 'morocco']),

-- SOCIAL (12 figures: 5 Europe, 4 Americas, 2 Asia, 1 Other)
('Susan B. Anthony', ARRAY['Anthony', 'Susan Anthony'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Susan_B_Anthony.jpg/800px-Susan_B_Anthony.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Susan_B_Anthony.jpg"}]'::jsonb,
 1820, 1906, 1852, 'Adams, Massachusetts', 42.6225, -73.1178,
 'American social reformer and women''s rights activist who played a pivotal role in the women''s suffrage movement. Never lived to see women get the vote.',
 ARRAY['activist', 'suffragist', 'modern', 'america', 'usa', 'female']),

('Elizabeth Blackwell', ARRAY['Blackwell'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Elizabeth_Blackwell.jpg/800px-Elizabeth_Blackwell.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Elizabeth_Blackwell.jpg"}]'::jsonb,
 1821, 1910, 1849, 'Bristol, England', 51.4552, -2.5967,
 'British-American physician and the first woman to receive a medical degree in the United States. Advocate for women in medicine.',
 ARRAY['physician', 'activist', 'modern', 'europe', 'england', 'female']),

('Florence Nightingale', ARRAY['Nightingale', 'Lady with the Lamp'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Florence_Nightingale_portrait.jpg/800px-Florence_Nightingale_portrait.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Florence_Nightingale_portrait.jpg"}]'::jsonb,
 1820, 1910, 1854, 'Florence, Italy', 43.7696, 11.2558,
 'British nurse who revolutionized nursing during the Crimean War. Founded modern nursing and statistical analysis in healthcare.',
 ARRAY['nurse', 'reformer', 'statistician', 'modern', 'europe', 'italy', 'female']),

('Marie Curie', ARRAY['Curie', 'Madame Curie'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Marie_Curie_c1920.jpg/800px-Marie_Curie_c1920.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Marie_Curie_c1920.jpg"}]'::jsonb,
 1867, 1934, 1903, 'Warsaw, Poland', 52.2297, 21.0122,
 'Polish physicist and chemist who conducted pioneering research on radioactivity. First woman to win a Nobel Prize and only person to win Nobel Prizes in two different sciences.',
 ARRAY['scientist', 'physicist', 'chemist', 'modern', 'europe', 'poland', 'female', 'nobel_laureate']),

('Rosa Luxemburg', ARRAY['Luxemburg'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Rosa_Luxemburg_1915.jpg/800px-Rosa_Luxemburg_1915.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Rosa_Luxemburg_1915.jpg"}]'::jsonb,
 1871, 1919, 1898, 'Zamość, Poland', 50.7184, 23.2519,
 'Polish Marxist revolutionary and philosopher who became a leader of the German Communist Party. Advocate for workers'' rights and democracy.',
 ARRAY['activist', 'philosopher', 'politics', 'modern', 'europe', 'poland', 'female']),

('Harriet Tubman', ARRAY['Tubman', 'Moses'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Harriet_Tubman2.jpg/800px-Harriet_Tubman2.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Harriet_Tubman2.jpg"}]'::jsonb,
 1822, 1913, 1850, 'Dorchester County, Maryland', 38.4500, -76.1667,
 'American abolitionist and social activist who escaped slavery and helped others do the same through the Underground Railroad. Union spy during Civil War.',
 ARRAY['activist', 'abolitionist', 'modern', 'america', 'usa', 'female']),

('Frederick Douglass', ARRAY['Douglass'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Frederick_Douglass_1856.jpg/800px-Frederick_Douglass_1856.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Frederick_Douglass_1856.jpg"}]'::jsonb,
 1818, 1895, 1845, 'Talbot County, Maryland', 38.7833, -76.0833,
 'American social reformer, abolitionist, writer, and statesman. Escaped slavery and became a leading voice in the abolitionist movement.',
 ARRAY['activist', 'abolitionist', 'writer', 'modern', 'america', 'usa']),

('Jane Addams', ARRAY['Addams'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Jane_Addams.jpg/800px-Jane_Addams.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Jane_Addams.jpg"}]'::jsonb,
 1860, 1935, 1889, 'Cedarville, Illinois', 40.3781, -83.8083,
 'American settlement activist, reformer, social worker, and Nobel Peace Prize winner. Founded Hull House in Chicago.',
 ARRAY['activist', 'social_worker', 'modern', 'america', 'usa', 'female', 'nobel_laureate']),

('Wangari Maathai', ARRAY['Maathai'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Wangari_Maathai_1940s.jpg/800px-Wangari_Maathai_1940s.jpg", "license": "CC BY 2.0", "credit": "Wangari Maathai", "source_url": "https://commons.wikimedia.org/wiki/File:Wangari_Maathai_1940s.jpg"}]'::jsonb,
 1940, 2011, 1977, 'Nyeri, Kenya', -0.4167, 36.9500,
 'Kenyan environmental and political activist who founded the Green Belt Movement. First African woman to win the Nobel Peace Prize.',
 ARRAY['activist', 'environmentalist', 'modern', 'africa', 'kenya', 'female', 'nobel_laureate']),

('Eleanor Roosevelt', ARRAY['Roosevelt', 'Mrs. Roosevelt'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Eleanor_Roosevelt_portrait_1933.jpg/800px-Eleanor_Roosevelt_portrait_1933.jpg", "license": "Public Domain", "credit": "United States Government", "source_url": "https://commons.wikimedia.org/wiki/File:Eleanor_Roosevelt_portrait_1933.jpg"}]'::jsonb,
 1884, 1962, 1921, 'New York City, New York', 40.7128, -74.0060,
 'American political figure and diplomat who served as First Lady. Advocate for civil rights, women''s rights, and human rights. Helped draft Universal Declaration.',
 ARRAY['activist', 'diplomat', 'modern', 'america', 'usa', 'female']),

('Mahatma Gandhi', ARRAY['Gandhi', 'Mahatma'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Mahatma-Gandhi%2C_studio%2C_1931.jpg/800px-Mahatma-Gandhi%2C_studio%2C_1931.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Mahatma-Gandhi,_studio,_1931.jpg"}]'::jsonb,
 1869, 1948, 1920, 'Porbandar, India', 21.6417, 69.6293,
 'Indian lawyer and anti-colonial nationalist who employed nonviolent resistance to lead the successful campaign for India''s independence from British rule.',
 ARRAY['activist', 'politics', 'modern', 'asia', 'india']),

('Malala Yousafzai', ARRAY['Malala'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Malala_Yousafzai_2015.jpg/800px-Malala_Yousafzai_2015.jpg", "license": "CC BY 2.0", "credit": "Russell Watkins/DFID", "source_url": "https://commons.wikimedia.org/wiki/File:Malala_Yousafzai_2015.jpg"}]'::jsonb,
 1997, NULL, 2014, 'Mingora, Pakistan', 34.7797, 72.3603,
 'Pakistani activist for female education and the youngest Nobel Prize laureate. Survived an assassination attempt by the Taliban at age 15.',
 ARRAY['activist', 'education', 'modern', 'asia', 'pakistan', 'female', 'nobel_laureate']),

-- BUSINESS (12 figures: 5 Europe, 4 Americas, 2 Asia, 1 Other)
('Andrew Carnegie', ARRAY['Carnegie'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Andrew_Carnegie%2C_three-quarter_length_portrait%2C_seated%2C_facing_slightly_left%2C_1913.jpg/800px-Andrew_Carnegie%2C_three-quarter_length_portrait%2C_seated%2C_facing_slightly_left%2C_1913.jpg", "license": "Public Domain", "credit": "Underwood & Underwood", "source_url": "https://commons.wikimedia.org/wiki/File:Andrew_Carnegie,_three-quarter_length_portrait,_seated,_facing_slightly_left,_1913.jpg"}]'::jsonb,
 1835, 1919, 1865, 'Dunfermline, Scotland', 56.0719, -3.4393,
 'Scottish-American industrialist and philanthropist who led the expansion of the American steel industry. Donated billions to charities and libraries.',
 ARRAY['industrialist', 'philanthropist', 'modern', 'europe', 'scotland']),

('John D. Rockefeller', ARRAY['Rockefeller'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/John_D._Rockefeller_1920.jpg/800px-John_D._Rockefeller_1920.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:John_D._Rockefeller_1920.jpg"}]'::jsonb,
 1839, 1937, 1870, 'Richford, New York', 44.4103, -72.1417,
 'American business magnate and philanthropist who founded Standard Oil and became the wealthiest person in history. Later donated billions to charity.',
 ARRAY['industrialist', 'philanthropist', 'oil', 'modern', 'america', 'usa']),

('Henry Ford', ARRAY['Ford'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Henry_ford_1919.jpg/800px-Henry_ford_1919.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:Henry_ford_1919.jpg"}]'::jsonb,
 1863, 1947, 1903, 'Dearborn, Michigan', 42.3223, -83.1763,
 'American industrialist who revolutionized the automobile industry with the assembly line. Founder of Ford Motor Company and pioneer of mass production.',
 ARRAY['industrialist', 'inventor', 'automotive', 'modern', 'america', 'usa']),

('J.P. Morgan', ARRAY['Morgan', 'J.P. Morgan'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/JPMorganJr.jpg/800px-JPMorganJr.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:JPMorganJr.jpg"}]'::jsonb,
 1837, 1913, 1895, 'Hartford, Connecticut', 41.7658, -72.6734,
 'American financier and banker who dominated corporate finance and industrial consolidation. Founder of J.P. Morgan & Co. and U.S. Steel.',
 ARRAY['banker', 'financier', 'industrialist', 'modern', 'america', 'usa']),

('Cornelius Vanderbilt', ARRAY['Vanderbilt', 'Commodore Vanderbilt'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Cornelius_Vanderbilt_-_1.jpg/800px-Cornelius_Vanderbilt_-_1.jpg", "license": "Public Domain", "credit": "Mathew Brady", "source_url": "https://commons.wikimedia.org/wiki/File:Cornelius_Vanderbilt_-_1.jpg"}]'::jsonb,
 1794, 1877, 1840, 'Staten Island, New York', 40.5795, -74.1502,
 'American business magnate who built his wealth through shipping and railroads. One of the wealthiest Americans in history.',
 ARRAY['industrialist', 'shipping', 'railroads', 'early_modern', 'america', 'usa']),

('John Jacob Astor', ARRAY['Astor'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/John_Jacob_Astor_-_Project_Gutenberg_eText_17035.jpg/800px-John_Jacob_Astor_-_Project_Gutenberg_eText_17035.jpg", "license": "Public Domain", "credit": "Unknown", "source_url": "https://commons.wikimedia.org/wiki/File:John_Jacob_Astor_-_Project_Gutenberg_eText_17035.jpg"}]'::jsonb,
 1763, 1848, 1786, 'Waldorf, Germany', 49.9833, 9.2833,
 'German-American businessman who made his fortune in the fur trade and real estate. Became the first millionaire in the United States.',
 ARRAY['businessman', 'fur_trade', 'real_estate', 'early_modern', 'europe', 'germany']),

('Andrew Mellon', ARRAY['Mellon'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Andrew_Mellon_1920.jpg/800px-Andrew_Mellon_1920.jpg", "license": "Public Domain", "credit": "Harris & Ewing", "source_url": "https://commons.wikimedia.org/wiki/File:Andrew_Mellon_1920.jpg"}]'::jsonb,
 1855, 1937, 1921, 'Pittsburgh, Pennsylvania', 40.4406, -79.9959,
 'American banker, businessman, and politician who served as Secretary of the Treasury. Known for tax policies that benefited wealthy.',
 ARRAY['banker', 'politician', 'industrialist', 'modern', 'america', 'usa']),

('Warren Buffett', ARRAY['Buffett', 'Oracle of Omaha'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Warren_Buffett_KU_Visit.jpg/800px-Warren_Buffett_KU_Visit.jpg", "license": "CC BY-SA 2.0", "credit": "Zennie Abraham", "source_url": "https://commons.wikimedia.org/wiki/File:Warren_Buffett_KU_Visit.jpg"}]'::jsonb,
 1930, NULL, 1965, 'Omaha, Nebraska', 41.2565, -95.9345,
 'American business magnate, investor, and philanthropist. Chairman and CEO of Berkshire Hathaway. One of the most successful investors in history.',
 ARRAY['investor', 'businessman', 'philanthropist', 'modern', 'america', 'usa']),

('Bill Gates', ARRAY['Gates'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Bill_Gates_2017.jpg/800px-Bill_Gates_2017.jpg", "license": "CC BY-SA 2.0", "credit": "World Economic Forum", "source_url": "https://commons.wikimedia.org/wiki/File:Bill_Gates_2017.jpg"}]'::jsonb,
 1955, NULL, 1975, 'Seattle, Washington', 47.6062, -122.3321,
 'American business magnate and philanthropist who co-founded Microsoft. Became one of the wealthiest people in the world through software.',
 ARRAY['businessman', 'software', 'philanthropist', 'modern', 'america', 'usa']),

('Jeff Bezos', ARRAY['Bezos'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_%2839074799225%29_%28cropped%29.jpg/800px-Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_%2839074799225%29_%28cropped%29.jpg", "license": "CC BY-SA 2.0", "credit": "Jimmy Baikovicius", "source_url": "https://commons.wikimedia.org/wiki/File:Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_(39074799225)_(cropped).jpg"}]'::jsonb,
 1964, NULL, 1994, 'Albuquerque, New Mexico', 35.0844, -106.6504,
 'American entrepreneur who founded Amazon. One of the wealthiest people in the world and pioneer of e-commerce.',
 ARRAY['entrepreneur', 'ecommerce', 'space', 'modern', 'america', 'usa']),

('Mukesh Ambani', ARRAY['Ambani'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Mukesh_Ambani_2018.jpg/800px-Mukesh_Ambani_2018.jpg", "license": "CC BY-SA 4.0", "credit": "Reliance Industries Limited", "source_url": "https://commons.wikimedia.org/wiki/File:Mukesh_Ambani_2018.jpg"}]'::jsonb,
 1957, NULL, 1981, 'Aden, Yemen', 12.7855, 45.0187,
 'Indian billionaire businessman and chairman of Reliance Industries. One of the richest people in the world through petrochemicals and telecommunications.',
 ARRAY['businessman', 'industrialist', 'petrochemicals', 'modern', 'asia', 'india']),

('Li Ka-shing', ARRAY['Li Ka-shing'],
 '[{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Li_Ka-shing_2015.jpg/800px-Li_Ka-shing_2015.jpg", "license": "CC BY-SA 4.0", "credit": "Li Ka-shing Foundation", "source_url": "https://commons.wikimedia.org/wiki/File:Li_Ka-shing_2015.jpg"}]'::jsonb,
 1928, NULL, 1950, 'Chaozhou, China', 23.6654, 116.6386,
 'Hong Kong businessman who founded Cheung Kong Holdings. Known for investments in real estate, ports, retail, and energy. One of Asia''s wealthiest.',
 ARRAY['businessman', 'real_estate', 'investor', 'modern', 'asia', 'china']);

-- Add comment
COMMENT ON TABLE figures IS 'Expanded to 131 total historical figures (31 original + 100 new) across 8 categories with geographic balance';
